renamed some libs, add ''see package request'' during aurpackages install, update path of the libs to /usr/ib/libpaura

diff --git a/paura b/paura
--- a/paura
+++ b/paura
@@ -1,6 +1,5 @@
 #!/bin/sh
 # Copyright (c) 2018 Spartaco Amadei <spamadei@gmail.com>
-
 # This program is free software: you can redistribute it and/or modify #
 # it under the terms of the GNU General Public License as published by #
 # the Free Software Foundation, either version 3 of the License, or    #
@@ -13,13 +12,10 @@
 #                                                                      #
 # You should have received a copy of the GNU General Public License    #
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.#
-
-
-
 #
 # pAURa, pacman AUR automatization: The new AUR helper that minimizes user interaction
 #
-LibDir='/usr/lib/paura'
+LibDir='/usr/lib/libpaura'
 Author="rez23"														              
 version="alpha1" 
 github="https://github.com/rez23/paura.git"
@@ -43,11 +39,10 @@ clonedir="${AURDEST:-$usercacheDir}/packages"
 ###
 #####
 # Lib
-source	${LibDir}/libaur.sh 
-source	${LibDir}/libpkg.sh 
-source	${LibDir}/libutils.sh 
-source  /usr/share/makepkg/*.sh
-
+source  /usr/share/makepkg/util/message.sh
+source ${LibDir}/libsearch.sh
+source ${LibDir}/libsync.sh
+source ${LibDir}/libutils.sh
 ###
 # Function
 ###
@@ -63,32 +58,40 @@ not_implemented_yet(){
 	echo "If you wont help visit:${github}"
 	}
 SyncPaura(){
-	testpkg
+	test_pkg
 	echo "*********************"
 	echo "**      pAURa     ****"
 	echo "*********************"
 	case ${OPTARG} in
-		y | *y* | *y | y* )
-			sudo pacman -S${OPTARG} 
-			[[ -z ${package} ]] && exit 0
-			if_close_exit
+		y | *y | y* )
+			[[ ${OPTARG} != ${package[0]} ]] && sudo pacman -S${OPTARG} ${corepackage}
+			[[ -z ${package} ]] && msg "Done!" && exit 0
 			;;
 		u | *u | u*)
-			sudo pacman -S${OPTARG}
+		[[ ${OPTARG} != ${package[0]} ]] && sudo pacman -S${OPTARG} ${corepackage}
 			sysupgrade=1
-			if_close_exit
 			;;
-		*) 
+		${package[0]}) 
 			msg3 "Searching packages..."
-			if_close_exit
-			[[ -n ${corepackage} ]] && msg "Getting core message" && pacman -S ${corepackage}
+			[[ -n ${corepackage} ]] && sudo pacman -S ${corepackage}
+			;;
+		*)
+					echo "$OPTARG isn't supported option"
+					echo "use -h | --help for some available options"
+				;;
 		esac
 	if [[ -n ${notfoundpkg} ]]; then
 			error "cant find ${notfoundpkg}"
 			exit 1
 	fi
 	get_pkg
-	process_pkg
+  install_pkg
+		if [[ $? == 0 ]]; then
+			msg "All packages are installed sucessfully"
+		else
+			error "An error as occured no packages will be installed" 
+			exit 1
+		fi
 }
 # OPTION
 
@@ -101,7 +104,6 @@ sleep 1
 # # # # # #
 # Option  
 # # # # # 
-	longopt=$1
 	while getopts ":S:R:Q:hvsq-:" opt; do
 	shift 1
 	declare -a package
@@ -117,10 +119,29 @@ sleep 1
 					paurainfo
 					;;
 				search)
+					while getopts "M:V:N:R:D:" soartopt; do
+						case ${soartopt} in
+							M)
+								sortorder=1
+								;;
+							V)
+								sortorder=2
+								;;
+							N)
+								sortorder=3
+								;;
+							R)
+								sortorder=4
+								;;
+							D)
+								sortorder=5
+								;;
+							esac
 					pkg_search
+					done
 					;;
 				testfunction)
-					testpkg
+					test_pkg
 					echo "core ${corepackage[*]}"
 	        echo "aur ${aurpackage[*]}"
 					;;
@@ -134,14 +155,14 @@ sleep 1
 					msg "Start system upgrade"
 					sudo pacman -Su ${package}
 					sysupgrade=1
-					testpkg
+					test_pkg
 					get_pkg
 					process_pkg
 					;;
 				sync)
 					msg "Searching packages..."
 					sudo pacman -Syy
-					testpkg package
+					test_pkg 
 					get_pkg
 					process_pkg
 					;;
@@ -166,7 +187,8 @@ sleep 1
 					;;
 				* )
 					SyncPaura
-					;;
+				;;
+				
 			esac
 		;;
 		"R")
